name: swa

services:
  db:
    container_name: swa-db
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - swa:/var/lib/postgresql/data
  server:
    container_name: swa-server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  swa:
